version: '2'
services:
  pinpoint-hbase:
    container_name: pinpoint-hbase
    image: wahyd4/pinpoint-hbase:1.6.2
    restart: always
    expose:
      - "2181"
      - "16010"
    ports:
      - "2181:2181"
      - "16010:16010"
    environment:
      TZ: "America/Recife"
    volumes:
      - hbase_data:/home/pinpoint/hbase
      - hbase_zookeeper_data:/home/pinpoint/zookeeper

  pinpoint-mysql:
    container_name: pinpoint-mysql
    restart: always
    image: marcosamm/pinpoint-mysql:1.6.2
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: pinpoint
      TZ: "America/Recife"
    volumes:
      - mysql_data:/var/lib/mysql
  
  pinpoint-collector:
    depends_on:
      - pinpoint-hbase
    container_name: pinpoint-collector
    image: wahyd4/pinpoint-collector:1.6.2
    restart: always
    expose:
      - "9994"
      - "9995"
      - "9996"
    ports:
      - "9994:9994"
      - "9995:9995/tcp"
      - "9996:9996/tcp"
      - "9995:9995/udp"
      - "9996:9996/udp"
    environment:
      HBASE_HOST: pinpoint-hbase
      HBASE_PORT: 2181
      COLLECTOR_TCP_PORT: 9994
      COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
      COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
      CLUSTER_ENABLE: 'true'
      CLUSTER_ZOOKEEPER_ADDRESS: pinpoint-hbase
      DISABLE_DEBUG: 'true'
      TZ: "America/Recife"
  
  pinpoint-web:
    depends_on:
      - pinpoint-hbase
      - pinpoint-mysql
    container_name: pinpoint-web
    image: wahyd4/pinpoint-web:1.6.2
    restart: always
    expose:
      - "8080"
    ports:
      - "28080:8080"
    environment:
      HBASE_HOST: pinpoint-hbase
      HBASE_PORT: 2181
      CLUSTER_ENABLE: 'true'
      CLUSTER_ZOOKEEPER_ADDRESS: pinpoint-hbase
      ADMIN_PASSWORD: admin123
      DISABLE_DEBUG: 'true'
      JDBC_DRIVER: com.mysql.jdbc.Driver
      JDBC_URL: jdbc:mysql://pinpoint-mysql:3306/pinpoint?characterEncoding=UTF-8
      JDBC_USERNAME: admin
      JDBC_PASSWORD: admin
      TZ: "America/Recife"

volumes:
  mysql_data:
  hbase_data:
  hbase_zookeeper_data:

#  only example
#  pinpoint-agent:
#    image: marcosamm/pinpoint-agent:1.6.2
#    net: "none"
#    restart: unless-stopped
#    volumes:
#      - /var/container_data/pinpoint-agent/log:/opt/app/pinpoint-agent/log:rw
#    environment:
#      COLLECTOR_IP: 192.168.99.100
#      COLLECTOR_TCP_PORT: 9994
#      COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
#      COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
#      DISABLE_DEBUG: 'true'
